version: "3.5"
services:
  pta-db:
    container_name: pta-db
    image: influxdb:1.7
    networks:
      - backend
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=aux
  pta-timescaledb:
    container_name: pta-timescaledb
    image: timescale/timescaledb:latest-pg10
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=timescale
    networks:
      - backend
    ports:
      - "5432:5432"
  pta-grafana:
    container_name: pta-grafana
    image: grafana/grafana:5.4.3
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - pta-db
  pta-app:
    container_name: pta-app
    build: ./app
    image: pta/app
    networks:
      - backend
    depends_on:
      - pta-db
networks:
  backend:
    driver: bridge
