version: "3.5"
services:
  pta-db:
    container_name: pta-db
    image: influxdb:1.7
    networks:
      - backend
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=aux
  pta-grafana:
    container_name: pta-grafana
    image: grafana/grafana:5.4.3
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - pta-db
  pta-app:
    container_name: pta-app
    build: ./app
    image: pta/app
    networks:
      - backend
    depends_on:
      - pta-db
networks:
  backend:
    driver: bridge
